Menpha/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.flatpages import views

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^messages/', include('postman.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
)

main/urls.py
# Urls.py Handwritten by google.com/+Nkansahrexford
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from . import views
from django.conf.urls.static import static
from Menpha import settings

urlpatterns = patterns('',
    # Normal url for back and forth communications
    url(r'^$', views.home, name='home'),
    url(r'^search/$', views.search, name='search'),
    url(r'^search/(?P<slug>\d+)/$', views.direct_search, name='direct_search'),
    url(r'^add/$', views.CreateImei.as_view(), name='add'),
    url(r'^detail/(?P<slug>\d+)/$', views.ItemDetail.as_view(), name='detail'),
    url(r'^edit/(?P<slug>\d+)/$', views.UpdateImei.as_view(), name='edit'),
    # url(r'^notify/email/(?P<slug>\d+)/$', views.notify_email, name='notify_email'),
    # url(r'^notify/(?P<slug>\d+)/$', views.notify, name='notify'),
    url(r'^delete/(?P<slug>\d+)/$', views.DeleteImei.as_view(), name='delete'),
    url(r'^mylist/$', views.ListImei.as_view(), name='mylist'),
    # url(r'^blog/$', views.ListBlog.as_view(), name='blog'),
    # url(r'^blog/(?P<slug>[\-\w]+)/$', views.BlogDetail.as_view(), name='blog_detail'),
    url(r'^privacy/$', TemplateView.as_view(template_name='privacy.html'), name='privacy'),
    url(r'^notify/thanks/$', login_required(TemplateView.as_view(template_name='notify-thanks.html')),),
    url(r'^email/thanks/$', login_required(TemplateView.as_view(template_name='email-thanks.html')),),

    url(r'^accounts/profile/$', views.profile, name='myAccount'),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


class Item(models.Model):
    """ Main model for the Menpha app. """
    device = models.CharField(max_length=250,)
    slug = models.SlugField(max_length=30, unique=True,)
    description = models.TextField(max_length=500)
    stolen = models.BooleanField(default=False)
    photo = ProcessedImageField(blank=True, null=True, upload_to='devices/',
        processors=[ResizeToFill(920, 480)], format='JPEG',
        options={'quality': 80})
    update_on = models.DateTimeField(auto_now=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User)

    def __unicode__(self):
        """ Returns device name """
        return self.device

    def get_absolute_url(self):
        """ For reverse url matching in views """
        return reverse('detail', kwargs={'slug': self.slug})


class siteWide(models.Model):
    meta_data = models.TextField(blank=True, default='meta things')
    plugins = models.TextField(blank=True, default='plugins')

    def __unicode__(self):
        return 'Meta Data and Plugin'

main/forms.py
from django import forms
from django.forms import ModelForm
from main.models import Item
from django.utils.translation import ugettext as _


class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ('device', 'slug', 'stolen', 'photo', 'description')
        # labels = {
        #     'device': _('Name of the device'),
        #     'slug': _('Unique Identifier ( IMEI, Serial number, etc )'),
        #     'stolen': _('Indicate state of device'),
        # }

class NotifyEmailForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    #sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)


# class NotifyForm(ModelForm):
#     class Meta:
#         model = Inbox
#         fields = ('msg_from', 'subject', 'message')

class ContactForm(forms.Form):
    #name = forms.CharField(max_length=100)
    subject = forms.CharField(max_length=300)
    sender = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)
    cc = forms.BooleanField(required=False)

    #device = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Device name'}))
    #imei = forms.CharField(max_length=15, 
    #   widget=forms.TextInput(attrs={'placeholder':'IMEI '})
    #   )
    #description = forms.CharField(widget=forms.Textarea(
    #   attrs={'placeholder':'Describe device', 
    #           'cols':50,
    #           'rows':4,
    #           'max_length': 350,
    #   }))

main/views.py
# Views.py Handwritten by google.com/+Nkansahrexford
from django.db.models import Q
from django.shortcuts import render
from main.models import Item
from main.forms import ItemForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.core.urlresolvers import reverse_lazy


def home(request):
    """Your homepage with search bar"""
    return render(request, 'home.html')


@login_required
def profile(request):
    '''Displays profile name under your Account'''
    account = User.objects.get(username=request.user.get_username())
    return render(request, 'account.html', {'object': account})


def search(request):
    """ Displays results of the searched query"""
    query = request.GET.get('query', '')
    if query:
        qset = Q(slug__iexact=query, stolen__iexact='True')
        results = Item.objects.filter(qset).distinct()
    else:
        results = []

    return render(request, "search.html", {
        'object_list': results,
        'query': query,
    })


def direct_search(request, slug):
    """If someone searches for Item using directly like /search/<slug>"""
    query = Q(slug__iexact=slug, stolen__iexact='s')
    results = Item.objects.filter(query).distinct()
    return render(request, 'search.html', {
        'results': results,
        'user': request.user,
        'query': slug
    })


class CreateImei(CreateView):
    """ Adds an object to database by a user in context.
    In Menpha v2.0, using REST for adding items."""
    template_name = 'add.html'
    form_class = ItemForm
    model = Item

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(CreateImei, self).form_valid(form)

    # requires login before allow saving
    @method_decorator(login_required())
    def dispatch(self, * args, ** kwargs):
        return super(CreateImei, self).dispatch(* args, ** kwargs)


class UpdateImei(UpdateView):
    """ Updates an object in context.

    If request.user is same as created_by value in model, dispatch
    function proceeds. Else PermissionDenied. Useful for preventing
    one user from editing item added by another user. """
    model = Item
    fields = ['device', 'slug', 'description', 'photo', 'stolen']
    template_name = 'item_form.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        pulled = Item.objects.get(slug=kwargs['slug'])
        if pulled.created_by == request.user:
            return super(UpdateImei, self).dispatch(request, *args, **kwargs)
        raise PermissionDenied


class DeleteImei(DeleteView):
    """ Deletes the the context object.
    If request.user is same as created_by value in model,
    dispatch function proceeds. Else PermissionDenied.

    Useful for preventing one user from deleting
    item added by another user. """
    model = Item
    context_object_name = 'to_delete'
    success_url = reverse_lazy('mylist')
    template_name = 'item_confirm_delete.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        grab = Item.objects.get(slug=kwargs['slug'])
        # Check if delete is authorized
        if grab.created_by == request.user:
            return super(DeleteImei, self).dispatch(request, *args, **kwargs)
        raise PermissionDenied


class ListImei(ListView):
    """Lists all the items added by a user."""
    model = Item
    template_name = 'mylist.html'

    def get_queryset(self):
        qset = Q(created_by=self.request.user)
        return Item.objects.filter(qset).distinct().order_by('-pub_date')

    @method_decorator(login_required())
    def dispatch(self, * args, ** kwargs):
        return super(ListImei, self).dispatch(* args, ** kwargs)


class ItemDetail(DetailView):
    model = Item
    template_name = 'detail.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'


# class ListBlog(ListView):
#     model = Blog
#     template_name = 'blog.html'
#     context_object_name = 'list'


# class BlogDetail(DetailView):
#     slug_field = 'slug'
#     slug_url_kwarg = 'slug'
#     model = Blog
#     context_object_name = 'detail'
#     template_name = 'blog_detail.html'


# @login_required
# def notify_email(request, slug):
#     """ Send notification email to original owner of device who lost it """
#     grab = Item.objects.get(slug=slug)
#     if request.method == "POST":
#         form = NotifyEmailForm(request.POST)
#         if form.is_valid():
#             subject = form.cleaned_data['subject']
#             message = form.cleaned_data['message']
#             sender = request.user.email
#             recipients = [grab.created_by.email]
#             recipients.append(sender)

#             send_mail(subject, message, sender, recipients)
#             return HttpResponseRedirect('/notify/thanks')  # Redirect after POST
#     else:
#         form = NotifyEmailForm()  # An unbound form
#     return render(request, 'send-mail.html', {'form': form, 'object': slug, })


# Error Pages. Referred from Settings.py
def file_not_found_404(request):
    return render(request, '404.html')


def server_error(request):
    return render(request, '500.html')


def perm_denied(request):
    return render(request, '403.html')

main/templates/postman/archives.html
{% extends "postman/base_folder.html" %}
{% load i18n %}
{% block pm_folder_title %}{% trans "Archived Messages" %}{% endblock %}
{% block pm_archive_button %}{% endblock %}
{% block pm_undelete_button %}{% endblock %}
{% block pm_footer_info %}
<p>{% trans "Messages in this folder will never be removed. You can use this folder for long term storage." %}</p>
{% endblock %}

main/templates/postman/base.html
<!DOCTYPE html>
<html>
{% load i18n %}
{% load postman_tags %}
{% load static %}
<head>
<title>{% block title %} Messaging {% endblock %}</title>
{% include 'include/stylesheets.html' %}
</head>

<body>
{% include 'include/navlist.html' %}
<div class="row">
    <div class="small-12 large-3 columns">
{% block postman_menu %}
<ul id="postman_menu">{% postman_unread as unread_count %}
 <li><a href="{% url 'postman_inbox' %}" class="btn wave-effect wave-light white-text">{% trans "Inbox" %}{% if unread_count %} <strong>({{ unread_count }})</strong>{% endif %}</a></li>
 <div class="divider" style="margin:5px 5px;"></div>
 <li><a href="{% url 'postman_sent' %}" class="btn wave-effect wave-light white-text">{% trans "Sent Messages" %}</a></li>
<div class="divider" style="margin:5px 5px;"></div>
 <li><a href="{% url 'postman_write' %}" class="btn wave-effect wave-light white-text">{% trans "Write" %}</a></li>
 <div class="divider" style="margin:5px 5px;"></div>
 <li><a href="{% url 'postman_archives' %}" class="btn wave-effect wave-light white-text">{% trans "Archives" %}</a></li>
 <div class="divider" style="margin:5px 5px;"></div>
 <li><a href="{% url 'postman_trash' %}" class="btn wave-effect wave-light white-text">{% trans "Trash" %}</a></li>
</ul>
{% endblock %}
</div>


<div class="small-12 large-9 columns">
{% block content %}
{% endblock %}
</div>
</div>
</body>
{% include 'include/javascripts.html' %}
</html>

main/templates/postman/base_folder.html
{% extends "postman/base.html" %} {% load i18n postman_tags %}{% load pagination_tags %}{% comment %} WARNING: 'pagination_tags' is a name from the django-pagination application. For convenience, the design of this template is done with the use of that application. Django-postman will still be working, even if that application is not installed, by providing a mock for the template tag library. If the real implementation is to be used, just make sure that 'pagination' is declared before 'postman' in the INSTALLED_APPS setting. {% endcomment %} {% block content %}
<div id="postman">
    <h3>{% block pm_folder_title %}{% endblock %}</h3> {% autopaginate pm_messages %} {% if invalid_page %}
    <p>{% trans "Sorry, this page number is invalid." %}</p>
    {% else %} {% if pm_messages %} {% block pm_by_modes %}
    <div id="pm_by_modes">
        <span class="pm-mode waves-effect waves-teal btn-flat">
{% if by_message %}
  <a href="{{ by_conversation_url }}">
{% endif %}
  {% trans "by conversation" %}
{% if by_message %}</a>
{% endif %}
</span> |
        <span class="pm_by_mode waves-effect waves-teal btn-flat">{% if by_conversation %}<a href="{{ by_message_url }}">{% endif %}{% trans "by message" %}{% if by_conversation %}</a>{% endif %}</span>
    </div>
    {% endblock pm_by_modes %}
    <div class="divider" style="margin:10px;"></div>
    <form action="{% block pm_form_action %}{% endblock %}" method="post">{% csrf_token %} {% block pm_form_buttons %}<span id="pm_buttons">
{% block pm_delete_button %}<button class="btn waves-effect waves-light" type="submit" onclick="this.form.action='{% url 'postman_delete' %}'">{% trans "Delete" %}</button>{% endblock %}
{% block pm_archive_button %}<button class="btn waves-effect waves-light"type="submit" onclick="this.form.action='{% url 'postman_archive' %}'">{% trans "Archive" %}</button>{% endblock %}
{% block pm_undelete_button %}<button type="submit" onclick="this.form.action='{% url 'postman_undelete' %}'">{% trans "Undelete" %}</button>{% endblock %}
</span>{% endblock %}
<div class="divider" style="margin:10px;"></div>
        <table id="pm_messages">
            <thead>
                <tr>
                    <th>{% trans "Action" %}</th>
                    {% block pm_sender_header %}
                    <th><a href="{% postman_order_by sender %}">{% trans "Sender" %}</a></th>{% endblock %} {% block pm_recipient_header %}
                    <th><a href="{% postman_order_by recipient %}">{% trans "Recipient" %}</a></th>{% endblock %}
                    <th><a href="{% postman_order_by subject %}">{% trans "Subject" %}</a></th>
                    <th><a href="{% postman_order_by date %}">{% block pm_date %}{% trans "Date" %}{% endblock %}</a></th>
                </tr>
            </thead>
            <tbody>{% for message in pm_messages %}
                <tr>
                    <td>
                        <input type="checkbox" {% if by_conversation and message.thread_id %}name="tpks" value="{{ message.thread_id }}" {% else %}name="pks" value="{{ message.pk }}" {% endif %} />
                        <label {% if by_conversation and message.thread_id %}for="tpks"{% else %}for="pks"{%endif %}></label>
                    </td>
                    {% block pm_sender_cell %}
                    <td>{{ message.obfuscated_sender|or_me:user }}{% if message.count %} ({{ message.count }}){% endif %}</td>{% endblock %} {% block pm_recipient_cell %}
                    <td>{{ message.obfuscated_recipient|or_me:user }}{% if message.count %} ({{ message.count }}){% endif %}</td>{% endblock %}
                    <td>{% if message.is_new %}<strong>{% endif %}{% if message.is_replied %}<em>{% endif %}
{% block pm_subject %}
    <a href="{% if by_conversation and message.thread_id %}{% url 'postman_view_conversation' message.thread_id %}{% else %}{{message.get_absolute_url }}{% endif %}?next={{ current_url|urlencode }}">
    {% include "postman/inc_subject_ex.html" %}
    </a>
{% endblock %}
   {% if message.is_replied %}</em>{% endif %}{% if message.is_new %}</strong>{% endif %}</td>
                    <td>{{ message.sent_at|compact_date:_("g:i A,M j,n/j/y") }}</td>
                </tr>{% endfor %}
            </tbody>
        </table>
    </form>
    {% paginate %} {% else %}
    <p>{% trans "No messages." %}</p>
    {% endif %} {% endif %} {% block pm_footer_info %}{% endblock %}
</div>
{% endblock content %}

main/templates/postman/base_write.html
{% extends "postman/base.html" %}
{% load i18n %}
{% block extrahead %}{{ block.super }}
{% if autocompleter_app.is_active %}
{# dj v1.4 #}{% load static %}
<script type="text/javascript"src="
{# using the available admin jQuery is enough: #}
 {# dj v1.4 #}{% static 'admin/js/jquery.min.js' %}
 {# dj v1.2/3 #}{# {% load adminmedia %}{% admin_media_prefix %}js/jquery.min.js #}
{# unless you really want your own: #}
 {# dj v1.2 #}{# {{ MEDIA_URL }}js/jquery.min.js #}
"></script>
{% if autocompleter_app.name == "ajax_select" %}{% if autocompleter_app.version == "1.1.4" or autocompleter_app.version == "1.1.5" %}<script type="text/javascript" src="{% static 'js/jquery.autocomplete.min.js' %}
"></script>
<link type="text/css" media="all" rel="stylesheet" href="{% static 'css/jquery.autocomplete.css' %}
" />{# else: for version 1.2.x use AJAX_SELECT_BOOTSTRAP + AJAX_SELECT_INLINES or arrange to include jqueryUI/js/css #}{% endif %}{% endif %}
{% endif %}
{% endblock %}
{% block content %}
<div id="postman">
<h1>{% block pm_write_title %}{% endblock %}</h1>
<form action="{% if next_url %}?next={{ next_url|urlencode }}{% endif %}" method="post">{% csrf_token %}
<table>
{% block pm_write_recipient %}{% endblock %}
<!-- {{ form.as_table }} -->
      <form class="col s12 z-depth-3" style="padding:20px;" action="." method="post" id="post-form" enctype="multipart/form-data">{% csrf_token %}
      {{ form.errors }}
        <div class="row">
          <div class="input-field col s12">
            <i class="mdi-communication-stay-primary-landscape prefix"></i>
            <input id="icon_prefix" type="text" id="id_recipients" name="recipients" {% if form.recipients.value %}value="{{ form.recipients.value }}" {% endif %} class="validate" required>
            <label for="icon_prefix">Recipient</label>
          </div>
          <div class="input-field col s12">
            <i class="mdi-editor-border-color prefix"></i>
            <input id="icon_telephone" type="text" id="id_subject" name="subject" {% if form.subject.value %}value="{{ form.subject.value }}" {% endif %} class="validate" required>
            <label for="icon_telephone">Subject</label>
          </div>
            <div class="input-field col s12">
              <i class="mdi-editor-mode-edit prefix"></i>
              <textarea id="icon_prefix2" class="materialize-textarea" id="id_body" required name="body"></textarea>
              <label for="icon_prefix2">Enter message here</label>
            </div>
            <div class="col s3" style="margin-top:20px;">
              <button type="submit" name="Submit" class="btn waves-effect waves-light"/>
              <i class="mdi-content-send left"></i>
              {% trans 'Send' %}
            </div>
            <div class="col s3" style="margin-top:20px;">
              <a href="{% url 'postman_inbox' %}" class="btn waves-effect waves-red red white-text">Cancel</a>
            </div>
        </div>
      </form>
</table>
</form>
</div>
{% endblock %}

main/templates/postman/inbox.html
{% extends "postman/base_folder.html" %}
{% load i18n %}
{% block pm_folder_title %}{% trans "Received Messages" %}{% endblock %}
{% block pm_undelete_button %}{% endblock %}
{% block pm_recipient_header %}{% endblock %}
{% block pm_date %}{% trans "Received" %}{% endblock %}
{% block pm_recipient_cell %}{% endblock %}

main/templates/postman/inc_subject_ex.html
{% comment %}
This file is intended to be included, such as in postman/base_folder.html:
    {% include "postman/inc_subject_ex.html" %}

It provides an extended subject, as a replacement to a simple {{ message.subject }} tag.
Enhancements are:
* limit the subject length to a few words
* if there is still room up to a maximum number of words, then add the very first words of the body,
  in a grey style.

Examples:
With a total of at most 12 words, and 5 words of subject.
With body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod."

With subject: "a subject of great interest for you":
"a subject of great interest ... - Lorem ipsum dolor sit amet, consectetur ..."

With subject: "a great interest":
"a great interest - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed ..."

{% endcomment %}{% load postman_tags %}{% with message.subject|truncatewords:5 as truncated_subject %}{{ truncated_subject }}
{% with truncated_subject|wordcount as subject_wc %}{% with 12|sub:subject_wc as wc %}{% if message.body and wc > 0 %} - <span style="color: grey">{{ message.body|truncatewords:wc }}</span>{% endif %}{% endwith %}{% endwith %}{% endwith %}

main/templates/postman/reply.html
{% extends "postman/base_write.html" %}
{% load i18n %}
{% block pm_write_title %}{% trans "Reply"%}{% endblock %}
{% block pm_write_recipient %}<tr><th><label>{% trans "Recipient" %}:</label></th><td>{{ recipient }}</td></tr>{% endblock %}

main/templates/postman/sent.html
{% extends "postman/base_folder.html" %}
{% load i18n %}
{% block pm_folder_title %}{% trans "Sent Messages" %}{% endblock %}
{% block pm_undelete_button %}{% endblock %}
{% block pm_sender_header %}{% endblock %}
{% block pm_date %}{% trans "Sent" %}{% endblock %}
{% block pm_sender_cell %}{% endblock %}

main/templates/postman/trash.html
{% extends "postman/base_folder.html" %}
{% load i18n %}
{% block pm_folder_title %}{% trans "Deleted Messages" %}{% endblock %}
{% block pm_delete_button %}{% endblock %}
{% block pm_archive_button %}{% endblock %}
{% block pm_subject %}{# no link #}
     {% include "postman/inc_subject_ex.html" %}
{% endblock %}
{% block pm_footer_info %}
<p>{% trans "Messages in this folder can be removed from time to time. For long term storage, use instead the archive folder." %}</p>
{% endblock %}

main/templates/postman/view.html
{% extends "postman/base.html" %}
{% load i18n %}{% load postman_tags %}
{% block content %}
<div id="postman">
<h3>{% if pm_messages|length > 1 %}{% trans "Conversation" %}{% else %}{% trans "Message" %}{% endif %}</h3>
{% for message in pm_messages %}
<div class="pm_message{% if message.is_pending %} pm_pending{% endif %}{% if message.is_rejected %} pm_rejected{% endif %}{% if message.sender == user and message.sender_archived or message.recipient == user and message.recipient_archived %} pm_archived{% endif %}{% if message.sender == user and message.sender_deleted_at or message.recipient == user and message.recipient_deleted_at %} pm_deleted{% endif %}{% if message.recipient == user and not message.read_at %} pm_unread{% endif %} z-depth-2" style="padding:15px;"> 
 <div class="pm_header">
  <span class="pm_sender">{{ message.obfuscated_sender|or_me:user }}</span> &raquo;
  <span class="pm_recipient">{{ message.obfuscated_recipient|or_me:user }}</span> |
  <span class="pm_date">{{ message.sent_at|date:"DATETIME_FORMAT"}}</span>
  <div class="divider"></div>
  <span class="pm_subject"><h5>{{ message.subject }}</h5></span>
  <div class="divider" style="margin-bottom:10px;"></div>
{% if message.is_rejected %}  
<div class="pm_status">{% trans "Rejected" %}{% if message.moderation_reason %}{% trans ":" %} {{ message.moderation_reason }}{% endif %}</div>{% endif %}
 </div>
 <div class="pm_body">{{ message.body|linebreaksbr }}</div>
</div>
<div class="divider" style="margin:20px;"></div>
{% if forloop.last %}
<form action="" method="post" class="z-depth-2" style="padding:15px;">{% csrf_token %}
<input type="hidden" {% if pm_messages|length > 1 and message.thread_id %}name="tpks" value="{{ message.thread_id }}"{% else %}name="pks" value="{{ message.pk }}"{% endif %} />
<a href="{{ next_url }}" class="waves-effect waves-teal btn-flat mdi-hardware-keyboard-backspace">{% trans "Back" %}</a>
<span id="pm_buttons">
<button type="submit" class="btn red waves-effect waves-light white-text mdi-action-delete" onclick="this.form.action='{% url 'postman_delete' %}?next={{ next_url|urlencode }}'">{% trans "Delete" %}</button>
{% if not archived %}<button type="submit" class="btn waves-effect waves-light white-text mdi-content-archive" onclick="this.form.action='{% url 'postman_archive' %}?next={{ next_url|urlencode }}'">{% trans "Archive" %}</button>{% endif %}
</span>
{% if reply_to_pk %}<a href="{% url 'postman_reply' reply_to_pk %}?next={{ next_url|urlencode }}" class="waves-effect waves-teal btn-flat mdi-content-reply">{% trans "Reply" %}</a>{% endif %}
</form>
{% if reply_to_pk %}
<div class="divider" style="margin:20px;"></div>
<h5>{% trans 'Quick reply' %}</h5>
<form action="{% url 'postman_reply' reply_to_pk %}?next={{ next_url|urlencode }}" method="post">{% csrf_token %}
<!-- <div id="pm_reply">{{ form.body }}</div> -->
<div class="input-field col s12">
  <i class="mdi-editor-mode-edit prefix"></i>
  <textarea id="icon_prefix2" class="materialize-textarea" id="id_body" required name="body"></textarea>
  <label for="icon_prefix2">Enter message here</label>
</div>
<button type="submit" class="btn waves-effect waves-light mdi-content-reply">{% trans 'Reply' %}</button>
</form>{% endif %}
{% endif %}
{% endfor %}
</div>
{% endblock %}

main/templates/postman/write.html
{% extends "postman/base_write.html" %}
{% load i18n %}
{% block pm_write_title %}{% trans "Write"%}{% endblock %}